#!groovy
//env.TOOLKIT_VER = "1.0-ks8"
//********* deplacara variables*************//
env.ORGA = "mkpof"
env.GIT_CRED = "GitHubPusher"
env.GIT_BASE_URL = "https://github.com"
env.GIT_DEVOPS_URL = "${env.GIT_BASE_URL}/${env.ORGA}/devops.git"
//******* Fin Declaracion Variable *****//
//
//***** Carga SharedLibs *****//
library(
    changelog: false,
    identifier: 'mkpof@master',
    retriever: modernSCM(
        [
            $class: 'GitSCMSource',
            credentialsId: 'GitHubPusher',
            remote: "${env.GIT_BASE_URL}/mkpof/toolkit_v1",
            traits: [
                [ $class: 'jenkins.plugins.git.traits.BranchDiscoveryTrait' ],
                [ $class: 'CleanAfterCheckoutTrait' ]
            ]
        ])
)

node () {
    stage("Carga 🕛") {
        // Detecto si se esta ejecutando un "Replay"
        currentBuild.getBuildCauses().each { cause ->
            if( cause._class == 'org.jenkinsci.plugins.workflow.cps.replay.ReplayCause') {
                mhUtilidades.Messages('"Replay" deshabilitado, por favor vuelva a iniciar el pipeline con el botón ▶️ RUN.', 'error')
                currentBuild.displayName = "⛔"
                currentBuild.description = '"Replay" deshabilitado, por favor vuelva a iniciar el pipeline con el botón ▶️ RUN.'
                sh "exit 1"
            }
            if( cause._class == 'org.jenkinsci.plugins.pipeline.modeldefinition.causes.RestartDeclarativePipelineCause') {
                mhUtilidades.Messages('"Restart" deshabilitado, por favor vuelva a iniciar el pipeline con el botón ▶️ RUN.', 'error')
                currentBuild.displayName = "⛔"
                currentBuild.description = '"Restart" deshabilitado, por favor vuelva a iniciar el pipeline con el botón ▶️ RUN.'
                sh "exit 1"
            }
        }

        //mhUtilidades.CleanWorkspace()

        mhUtilidades.CurrentDate() {}
        //env.STARTDATE = env.tdatealm
        //mhUtilidades.CurrentDate()
        timeout(time: 3, unit: 'MINUTES') 
           mhUserInputs(time: 4)
        }

        mhUtilidades.Messages("Mensaje en el stage de carga", 'success')
        mhDebug.printEnvVars()
    }

}

println("Pasamos el primer STAGE")